// Generates the frontend's contract types from the backend's JSON Schema (PLAN 6.4).
//
//   node scripts/gen-types.mjs             write src/lib/contract.gen.ts
//   node scripts/gen-types.mjs --check     fail when that file is not what the schema generates
//   node scripts/gen-types.mjs --fixtures  write src/__tests__/fixtures/examples.gen.ts from
//                                          docs/examples/*/response.json (git-ignored)
//
// A JSON import would widen the `kind` and `type` literals to `string`, so a recorded response
// would not be accepted as a `QueryResponse`. A generated .ts object literal is checked against
// the generated types at compile time instead.

import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const frontend = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = path.resolve(frontend, "../docs/schema/contract.v1.schema.json");
const examplesDir = path.resolve(frontend, "../docs/examples");
const typesPath = path.join(frontend, "src/lib/contract.gen.ts");
const fixturesPath = path.join(frontend, "src/__tests__/fixtures/examples.gen.ts");

const BANNER = `/**
 * Generated by scripts/gen-types.mjs from docs/schema/contract.v1.schema.json.
 * DO NOT EDIT BY HAND. Change the backend's models and run \`pnpm gen:types\`.
 */`;

/**
 * Every node that has a $ref becomes { $ref } alone. Otherwise each use site that carries a
 * sibling description or default is compiled as a separate, numbered copy of the referenced type.
 */
function keepOnlyRefs(node) {
  if (Array.isArray(node)) {
    return node.map(keepOnlyRefs);
  }
  if (node !== null && typeof node === "object") {
    if (typeof node.$ref === "string") {
      return { $ref: node.$ref };
    }
    return Object.fromEntries(Object.entries(node).map(([key, value]) => [key, keepOnlyRefs(value)]));
  }
  return node;
}

async function generateTypes() {
  if (!existsSync(schemaPath)) {
    throw new Error(`The schema is missing: ${schemaPath}. The backend writes it with its docs generator.`);
  }
  const schema = keepOnlyRefs(JSON.parse(await readFile(schemaPath, "utf8")));
  return compile(schema, "Contract", { additionalProperties: false, bannerComment: BANNER });
}

const NEW_FILTER_LISTS = [
  "exclude_statuses",
  "sexes",
  "age_groups",
  "allocations",
  "maskings",
  "primary_purposes",
  "has_results",
  "intervention_models",
];
const NEW_APPLIED_LISTS = ["sex", "age_group", "allocation", "masking", "primary_purpose", "has_results", "intervention_model"];

/**
 * A response recorded before a contract addition lacks the new keys, and the fixtures are compiled
 * against the current types. Fill each new key with its "nothing" value (an empty list or null) so
 * that old recordings keep compiling; re-recording the examples makes this a no-op.
 */
function upgradeRecording(response) {
  const meta = response.meta;
  if (!meta) return response;
  const applied = meta.filters;
  if (applied) {
    for (const key of NEW_APPLIED_LISTS) applied[key] ??= [];
    applied.exclude ??= { drug_name: [], condition: [], sponsor: [], country: [], term: [], status: [] };
  }
  const plan = meta.plan;
  if (plan) {
    for (const key of NEW_FILTER_LISTS) plan.filters[key] ??= [];
    if (plan.analysis.kind === "aggregate" || plan.analysis.kind === "total") {
      plan.analysis.statistic ??= null;
      plan.analysis.of ??= null;
    }
  }
  const measure = meta.interpretation?.measure;
  if (measure) measure.unit ??= measure.of === "trials" ? "trials" : measure.of;
  return response;
}

async function generateFixtures() {
  const entries = existsSync(examplesDir) ? await readdir(examplesDir, { withFileTypes: true }) : [];
  const examples = {};
  for (const entry of entries.filter((item) => item.isDirectory()).sort((a, b) => a.name.localeCompare(b.name))) {
    const file = path.join(examplesDir, entry.name, "response.json");
    if (existsSync(file)) {
      examples[entry.name] = upgradeRecording(JSON.parse(await readFile(file, "utf8")));
    }
  }
  return `// Generated by scripts/gen-types.mjs --fixtures from docs/examples/*/response.json. Git-ignored.
import type { QueryResponse } from "@/lib/contract.gen";

export const examples: Record<string, QueryResponse> = ${JSON.stringify(examples, null, 2)};
`;
}

const mode = process.argv[2];

if (mode === "--check") {
  const expected = await generateTypes();
  const actual = existsSync(typesPath) ? await readFile(typesPath, "utf8") : null;
  if (actual !== expected) {
    console.error("src/lib/contract.gen.ts is out of date with docs/schema/contract.v1.schema.json. Run: pnpm gen:types");
    process.exit(1);
  }
  console.log("src/lib/contract.gen.ts is up to date.");
} else if (mode === "--fixtures") {
  await mkdir(path.dirname(fixturesPath), { recursive: true });
  await writeFile(fixturesPath, await generateFixtures());
  console.log("Wrote src/__tests__/fixtures/examples.gen.ts");
} else if (mode === undefined) {
  await writeFile(typesPath, await generateTypes());
  console.log("Wrote src/lib/contract.gen.ts");
} else {
  console.error(`Unknown option ${mode}. Use --check or --fixtures, or no option to write the types.`);
  process.exit(2);
}
