/**
 * Generated by scripts/gen-types.mjs from docs/schema/contract.v1.schema.json.
 * DO NOT EDIT BY HAND. Change the backend's models and run `pnpm gen:types`.
 */

export type QueryResponse = VisualizationResponse | ClarificationResponse | MessageResponse;
export type Visualization = BarChart | TimeSeries | Histogram | ScatterPlot | NetworkGraph | Table | Metric;

/**
 * Every top-level type of the contract, one field each.
 */
export interface Contract {
  query_request: QueryRequest;
  analysis_request: AnalysisRequest;
  query_plan: QueryPlan;
  query_response: QueryResponse;
  error_response: ErrorResponse;
}
/**
 * A question about clinical trials, with optional structured fields.
 *
 * Strings are trimmed and unknown keys are rejected. Rules across fields:
 *
 * 1. Structured filter fields are ANDed with what the question says. Where they conflict, the field
 *    wins: it replaces the planner's value for the same entity kind or filter family, and the
 *    override is recorded in `meta.interpretation.adjustments`.
 * 2. A structured entity field whose value is one of the compared values does not become an extra
 *    filter; the comparison is kept.
 * 3. Entity arrays mean "all of"; enum arrays mean "any of". A comparison is always explicit:
 *    `compare` in the request or an "A vs B" in the question.
 * 4. `group_by`, `time_unit`, `top_n` and `chart_type` replace the planner's choices.
 * 5. Every structured field is shown to the model, so "this drug" in the question resolves to
 *    `drug_name`.
 * 6. With `previous`, the message may be a follow-up: the planner edits the previous plan, or ignores it
 *    when the message is unrelated. A name, year or filter may then come from the message or be carried
 *    over unchanged from the previous plan; one that is in neither is rejected.
 * 7. `meta.filters` in every response repeats the filter fields in canonical form (arrays for list
 *    fields, every key present), so it can be sent back as request fields. For that reason every list
 *    field accepts an empty array as "no filter", the same as null.
 */
export interface QueryRequest {
  /**
   * The natural-language question. Tabs and line breaks become spaces and runs of whitespace collapse before validation, because a pasted question can carry line breaks. Then 3 to 1,000 characters, at least one letter and no other control characters.
   */
  query: string;
  /**
   * Drugs the trials must test, up to 5, each 1 to 200 characters; a single string is accepted. A trial must match all of them. Searched with the registry's intervention search, so brand and code names resolve (Keytruda and MK-3475 return the same trials as pembrolizumab).
   */
  drug_name?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Conditions the trials must study; same rules as `drug_name`, searched with the registry's condition search.
   */
  condition?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Lead-sponsor names; same rules as `drug_name`, searched in the lead sponsor name.
   */
  sponsor?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Countries; same rules as `drug_name`. Each must resolve to one of the registry's country names (common aliases and ISO alpha-2 or alpha-3 codes are accepted), otherwise the request is refused with close matches. A trial must list a site in every named country.
   */
  country?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Other search words, matched anywhere in the record; same rules as `drug_name`.
   */
  term?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Phases, any of. Lenient spellings are normalised before validation: 'Phase 2', 'phase2', '2' and 'II' become PHASE2, and 'Phase 2/3' becomes both PHASE2 and PHASE3; a single value is accepted. 'Lists this phase' semantics, as on the registry's website: PHASE2 also matches Phase 1/Phase 2 and Phase 2/Phase 3 trials.
   */
  trial_phase?: ("EARLY_PHASE1" | "PHASE1" | "PHASE2" | "PHASE3" | "PHASE4" | "NA")[] | null;
  /**
   * Study-level overall statuses, any of.
   */
  status?:
    | (
        | "NOT_YET_RECRUITING"
        | "RECRUITING"
        | "ENROLLING_BY_INVITATION"
        | "ACTIVE_NOT_RECRUITING"
        | "COMPLETED"
        | "SUSPENDED"
        | "TERMINATED"
        | "WITHDRAWN"
        | "AVAILABLE"
        | "NO_LONGER_AVAILABLE"
        | "TEMPORARILY_NOT_AVAILABLE"
        | "APPROVED_FOR_MARKETING"
        | "WITHHELD"
        | "UNKNOWN"
      )[]
    | null;
  /**
   * Study types, any of.
   */
  study_type?: ("INTERVENTIONAL" | "OBSERVATIONAL" | "EXPANDED_ACCESS")[] | null;
  /**
   * Classes of the lead sponsor, any of.
   */
  sponsor_class?:
    ("NIH" | "FED" | "OTHER_GOV" | "INDIV" | "INDUSTRY" | "NETWORK" | "AMBIG" | "OTHER" | "UNKNOWN")[] | null;
  /**
   * Trials with at least one intervention of these types, any of.
   */
  intervention_type?:
    | (
        | "BEHAVIORAL"
        | "BIOLOGICAL"
        | "COMBINATION_PRODUCT"
        | "DEVICE"
        | "DIAGNOSTIC_TEST"
        | "DIETARY_SUPPLEMENT"
        | "DRUG"
        | "GENETIC"
        | "PROCEDURE"
        | "RADIATION"
        | "OTHER"
      )[]
    | null;
  /**
   * Sexes the trials accept, any of.
   */
  sex?: ("FEMALE" | "MALE" | "ALL")[] | null;
  /**
   * Age groups the trials include, any of.
   */
  age_group?: ("CHILD" | "ADULT" | "OLDER_ADULT")[] | null;
  /**
   * Allocation of interventional trials, any of (RANDOMIZED, NON_RANDOMIZED, NA).
   */
  allocation?: ("RANDOMIZED" | "NON_RANDOMIZED" | "NA")[] | null;
  /**
   * Masking of interventional trials, any of.
   */
  masking?: ("NONE" | "SINGLE" | "DOUBLE" | "TRIPLE" | "QUADRUPLE")[] | null;
  /**
   * Primary purposes, any of.
   */
  primary_purpose?:
    | (
        | "TREATMENT"
        | "PREVENTION"
        | "DIAGNOSTIC"
        | "ECT"
        | "SUPPORTIVE_CARE"
        | "SCREENING"
        | "HEALTH_SERVICES_RESEARCH"
        | "BASIC_SCIENCE"
        | "DEVICE_FEASIBILITY"
        | "OTHER"
      )[]
    | null;
  /**
   * 'true': results posted; 'false': none posted.
   */
  has_results?: ("true" | "false")[] | null;
  /**
   * Assignment models of interventional trials, any of.
   */
  intervention_model?: ("PARALLEL" | "CROSSOVER" | "FACTORIAL" | "SEQUENTIAL" | "SINGLE_GROUP")[] | null;
  /**
   * First year, inclusive, of the date named by `date_field`. Not after `end_year`.
   */
  start_year?: number | null;
  /**
   * Last year, inclusive, of the date named by `date_field`. Not before `start_year`.
   */
  end_year?: number | null;
  /**
   * Which date the year bounds apply to. Null means the date on the time axis when the chart has one, otherwise the study start date.
   */
  date_field?: ("start_date" | "primary_completion_date" | "completion_date" | "first_posted_date") | null;
  /**
   * Compare these as series. Replaces any comparison found in the question.
   */
  compare?: CompareSpec | null;
  /**
   * Leave out trials that match any listed entity or have any listed status ('excluding diabetes', 'without terminated studies'). Replaces what the planner read for the same entity kind or for statuses; an empty object is no exclusion.
   */
  exclude?: ExcludeSpec | null;
  /**
   * Analysis hint: the first key is the axis, the second the series. The second key must be one of the closed dimensions (phase, overall_status, study_type, sponsor_class, intervention_type, sex, age_group, allocation, masking, primary_purpose, has_results, intervention_model). Overrides what the planner chose. Required when `options.planner` is 'structured'.
   */
  group_by?:
    | [
        | "phase"
        | "overall_status"
        | "study_type"
        | "sponsor_class"
        | "intervention_type"
        | "sex"
        | "age_group"
        | "allocation"
        | "masking"
        | "primary_purpose"
        | "has_results"
        | "intervention_model"
        | "country"
        | "state"
        | "sponsor"
        | "drug"
        | "condition"
        | "start_date"
        | "primary_completion_date"
        | "completion_date"
        | "first_posted_date"
        | "enrollment"
      ]
    | [
        (
          | "phase"
          | "overall_status"
          | "study_type"
          | "sponsor_class"
          | "intervention_type"
          | "sex"
          | "age_group"
          | "allocation"
          | "masking"
          | "primary_purpose"
          | "has_results"
          | "intervention_model"
          | "country"
          | "state"
          | "sponsor"
          | "drug"
          | "condition"
          | "start_date"
          | "primary_completion_date"
          | "completion_date"
          | "first_posted_date"
          | "enrollment"
        ),
        (
          | "phase"
          | "overall_status"
          | "study_type"
          | "sponsor_class"
          | "intervention_type"
          | "sex"
          | "age_group"
          | "allocation"
          | "masking"
          | "primary_purpose"
          | "has_results"
          | "intervention_model"
          | "country"
          | "state"
          | "sponsor"
          | "drug"
          | "condition"
          | "start_date"
          | "primary_completion_date"
          | "completion_date"
          | "first_posted_date"
          | "enrollment"
        )
      ]
    | null;
  /**
   * Analysis hint: bucket width for a date dimension.
   */
  time_unit?: ("year" | "quarter" | "month") | null;
  /**
   * How many categories or rows to keep. Default 15, or 10 for the rows of a trial list. Network sizes are fixed in v1.
   */
  top_n?: number | null;
  /**
   * A preference. Honoured when valid for the data shape, otherwise ignored with a warning.
   */
  chart_type?:
    ("bar_chart" | "time_series" | "histogram" | "scatter_plot" | "network_graph" | "table" | "metric") | null;
  /**
   * The previous turn, for a follow-up such as 'now split that by phase'. Null (the default) is a new conversation. Part of the plan cache key.
   */
  previous?: PreviousTurn | null;
  options?: RequestOptions;
}
/**
 * Values of one entity kind to compare side by side, one series each.
 */
export interface CompareSpec {
  field: "drug_name" | "condition" | "sponsor" | "country";
  /**
   * @minItems 2
   * @maxItems 5
   */
  values:
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string];
}
/**
 * Trials to leave out: those that match any of these entities or have any of these statuses.
 */
export interface ExcludeSpec {
  /**
   * Drugs to leave out; same searches as the filter fields.
   */
  drug_name?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Conditions to leave out.
   */
  condition?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Lead sponsors to leave out.
   */
  sponsor?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Countries to leave out (any site there).
   */
  country?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Other search words to leave out.
   */
  term?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | null;
  /**
   * Overall statuses to leave out.
   */
  status?:
    | (
        | "NOT_YET_RECRUITING"
        | "RECRUITING"
        | "ENROLLING_BY_INVITATION"
        | "ACTIVE_NOT_RECRUITING"
        | "COMPLETED"
        | "SUSPENDED"
        | "TERMINATED"
        | "WITHDRAWN"
        | "AVAILABLE"
        | "NO_LONGER_AVAILABLE"
        | "TEMPORARILY_NOT_AVAILABLE"
        | "APPROVED_FOR_MARKETING"
        | "WITHHELD"
        | "UNKNOWN"
      )[]
    | null;
}
/**
 * The previous turn of a conversation: what was asked and the plan that answered it.
 *
 * The service keeps no session. The client sends back the question and `meta.plan` of the answer it
 * shows, and the planner reads the new message as a follow-up to them.
 */
export interface PreviousTurn {
  /**
   * The previous question as sent (`meta.query`); null when the previous turn had none.
   */
  query: string | null;
  plan: QueryPlan;
}
export interface QueryPlan {
  /**
   * One sentence restating what will be counted and how it is grouped. No figures other than those in the question.
   */
  interpretation: string;
  /**
   * Named drugs, conditions, sponsors, countries or other terms.
   *
   * @maxItems 12
   */
  entities:
    | []
    | [Entity]
    | [Entity, Entity]
    | [Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity, Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity]
    | [Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity, Entity];
  filters: PlanFilters;
  analysis: Aggregate | Total | Relate | Network | TrialList | Clarify | Unsupported;
  /**
   * Only when the user names a chart form; otherwise null.
   */
  chart_preference:
    ("bar_chart" | "time_series" | "histogram" | "scatter_plot" | "network_graph" | "table" | "metric") | null;
  /**
   * Words copied from the question that ask to make part of the chart look different (highlight, mark, annotate, colour); empty otherwise, and empty for most questions. Never a counting rule or a wish for a clear chart, and never a reason for 'unsupported'.
   *
   * @maxItems 5
   */
  unapplied:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string];
}
export interface Entity {
  kind: "drug" | "condition" | "sponsor" | "country" | "term";
  /**
   * The words exactly as they appear in the question or in a structured field. Never translate, expand, correct or add a name.
   */
  value: string;
  /**
   * 'filter': every counted trial must match. 'compare': one side of an 'A vs B' comparison. 'exclude': no counted trial may match ('excluding', 'without', 'not involving').
   */
  role: "filter" | "compare" | "exclude";
}
export interface PlanFilters {
  /**
   * Empty unless the question restricts phase.
   */
  phases: ("EARLY_PHASE1" | "PHASE1" | "PHASE2" | "PHASE3" | "PHASE4" | "NA")[];
  /**
   * Empty unless the question restricts status. 'recruiting' means RECRUITING only.
   */
  statuses: (
    | "NOT_YET_RECRUITING"
    | "RECRUITING"
    | "ENROLLING_BY_INVITATION"
    | "ACTIVE_NOT_RECRUITING"
    | "COMPLETED"
    | "SUSPENDED"
    | "TERMINATED"
    | "WITHDRAWN"
    | "AVAILABLE"
    | "NO_LONGER_AVAILABLE"
    | "TEMPORARILY_NOT_AVAILABLE"
    | "APPROVED_FOR_MARKETING"
    | "WITHHELD"
    | "UNKNOWN"
  )[];
  /**
   * Empty unless the question leaves statuses out, e.g. 'exclude terminated studies'.
   */
  exclude_statuses: (
    | "NOT_YET_RECRUITING"
    | "RECRUITING"
    | "ENROLLING_BY_INVITATION"
    | "ACTIVE_NOT_RECRUITING"
    | "COMPLETED"
    | "SUSPENDED"
    | "TERMINATED"
    | "WITHDRAWN"
    | "AVAILABLE"
    | "NO_LONGER_AVAILABLE"
    | "TEMPORARILY_NOT_AVAILABLE"
    | "APPROVED_FOR_MARKETING"
    | "WITHHELD"
    | "UNKNOWN"
  )[];
  /**
   * Empty unless the question restricts study type.
   */
  study_types: ("INTERVENTIONAL" | "OBSERVATIONAL" | "EXPANDED_ACCESS")[];
  /**
   * Empty unless the question restricts the kind of sponsor, e.g. industry.
   */
  sponsor_classes: ("NIH" | "FED" | "OTHER_GOV" | "INDIV" | "INDUSTRY" | "NETWORK" | "AMBIG" | "OTHER" | "UNKNOWN")[];
  /**
   * Empty unless the question restricts the kind of intervention.
   */
  intervention_types: (
    | "BEHAVIORAL"
    | "BIOLOGICAL"
    | "COMBINATION_PRODUCT"
    | "DEVICE"
    | "DIAGNOSTIC_TEST"
    | "DIETARY_SUPPLEMENT"
    | "DRUG"
    | "GENETIC"
    | "PROCEDURE"
    | "RADIATION"
    | "OTHER"
  )[];
  /**
   * Empty unless the question restricts the sexes eligible.
   */
  sexes: ("FEMALE" | "MALE" | "ALL")[];
  /**
   * Empty unless the question restricts the age group.
   */
  age_groups: ("CHILD" | "ADULT" | "OLDER_ADULT")[];
  /**
   * Empty unless the question restricts allocation: 'randomized' is RANDOMIZED.
   */
  allocations: ("RANDOMIZED" | "NON_RANDOMIZED" | "NA")[];
  /**
   * Empty unless the question restricts masking, e.g. 'double-blind' is DOUBLE.
   */
  maskings: ("NONE" | "SINGLE" | "DOUBLE" | "TRIPLE" | "QUADRUPLE")[];
  /**
   * Empty unless the question restricts the primary purpose, e.g. 'prevention trials'.
   */
  primary_purposes: (
    | "TREATMENT"
    | "PREVENTION"
    | "DIAGNOSTIC"
    | "ECT"
    | "SUPPORTIVE_CARE"
    | "SCREENING"
    | "HEALTH_SERVICES_RESEARCH"
    | "BASIC_SCIENCE"
    | "DEVICE_FEASIBILITY"
    | "OTHER"
  )[];
  /**
   * Empty unless the question restricts whether results are posted: ['true'] or ['false'].
   */
  has_results: ("true" | "false")[];
  /**
   * Empty unless the question restricts the assignment model, e.g. 'crossover'.
   */
  intervention_models: ("PARALLEL" | "CROSSOVER" | "FACTORIAL" | "SEQUENTIAL" | "SINGLE_GROUP")[];
  /**
   * One item for every non-empty list above.
   */
  evidence: FilterEvidence[];
  /**
   * Which date year_from and year_to apply to; null lets the service decide.
   */
  date_field: ("start_date" | "primary_completion_date" | "completion_date" | "first_posted_date") | null;
  /**
   * First year, inclusive; null if the question gives none.
   */
  year_from: number | null;
  /**
   * Last year, inclusive; null if the question gives none.
   */
  year_to: number | null;
}
export interface FilterEvidence {
  family:
    | "phases"
    | "statuses"
    | "exclude_statuses"
    | "study_types"
    | "sponsor_classes"
    | "intervention_types"
    | "sexes"
    | "age_groups"
    | "allocations"
    | "maskings"
    | "primary_purposes"
    | "has_results"
    | "intervention_models";
  /**
   * The words of the question that state this filter, copied verbatim.
   */
  phrase: string;
}
export interface Aggregate {
  kind: "aggregate";
  /**
   * What trials are counted by: a category, a date or enrollment size.
   */
  dimension:
    | "phase"
    | "overall_status"
    | "study_type"
    | "sponsor_class"
    | "intervention_type"
    | "sex"
    | "age_group"
    | "allocation"
    | "masking"
    | "primary_purpose"
    | "has_results"
    | "intervention_model"
    | "country"
    | "state"
    | "sponsor"
    | "drug"
    | "condition"
    | "start_date"
    | "primary_completion_date"
    | "completion_date"
    | "first_posted_date"
    | "enrollment";
  /**
   * A second, closed dimension that splits the first; null otherwise.
   */
  series:
    | (
        | "phase"
        | "overall_status"
        | "study_type"
        | "sponsor_class"
        | "intervention_type"
        | "sex"
        | "age_group"
        | "allocation"
        | "masking"
        | "primary_purpose"
        | "has_results"
        | "intervention_model"
      )
    | null;
  /**
   * Only for date dimensions; null lets the service use year.
   */
  time_unit: ("year" | "quarter" | "month") | null;
  /**
   * Only when the user asks for a number of items; otherwise null.
   */
  top_n: number | null;
  /**
   * Null counts trials. 'median', 'mean' or 'sum' of the numeric field `of` instead.
   */
  statistic: ("median" | "mean" | "sum") | null;
  /**
   * The numeric field of a statistic; null when counting.
   */
  of: ("enrollment" | "duration_months" | "site_count") | null;
}
export interface Total {
  kind: "total";
  /**
   * Null counts trials. 'median', 'mean' or 'sum' of the numeric field `of` instead.
   */
  statistic: ("median" | "mean" | "sum") | null;
  /**
   * The numeric field of a statistic; null when counting.
   */
  of: ("enrollment" | "duration_months" | "site_count") | null;
}
export interface Relate {
  kind: "relate";
  x: "enrollment" | "duration_months" | "site_count";
  y: "enrollment" | "duration_months" | "site_count";
  color_by:
    | (
        | "phase"
        | "overall_status"
        | "study_type"
        | "sponsor_class"
        | "intervention_type"
        | "sex"
        | "age_group"
        | "allocation"
        | "masking"
        | "primary_purpose"
        | "has_results"
        | "intervention_model"
      )
    | null;
}
export interface Network {
  kind: "network";
  source: "sponsor" | "drug" | "condition" | "country";
  /**
   * The same kind as source for co-occurrence, e.g. drug and drug.
   */
  target: "sponsor" | "drug" | "condition" | "country";
  /**
   * 'same_arm' when the question is about combinations; null lets the service decide.
   */
  link: ("same_trial" | "same_arm") | null;
}
export interface TrialList {
  kind: "trial_list";
  sort_by: "enrollment" | "start_date" | "completion_date" | "first_posted_date";
  order: "desc" | "asc";
  /**
   * Only when the user gives a number; otherwise null.
   */
  limit: number | null;
}
export interface Clarify {
  kind: "clarify";
  reason: "missing_entity" | "ambiguous_request";
  missing: ("drug_name" | "condition" | "sponsor" | "country" | "compare" | "group_by")[];
}
export interface Unsupported {
  kind: "unsupported";
  category:
    | "not_about_clinical_trials"
    | "needs_data_not_in_registry"
    | "single_trial_lookup"
    | "analysis_not_supported"
    | "other";
  /**
   * One sentence. No figures other than those in the question.
   */
  reason: string;
}
/**
 * Behaviour switches of one request; `meta.options` echoes the effective values.
 */
export interface RequestOptions {
  /**
   * 'llm': the model writes the plan (503 `planner_unavailable` when no model is configured). 'structured': never call a model; the plan is built from the request fields and `group_by` is required. The question text is then not interpreted, and the response says so. Ignored by `POST /v1/analyses`.
   */
  planner?: "llm" | "structured";
  /**
   * Trials cited for each datum; 0 disables citations.
   */
  citations_per_datum?: number;
  /**
   * 'broad': the registry's intervention search (names, other names, titles, descriptions, synonyms). 'name_only': intervention names and their synonyms only. The two give different counts, so the definition used is always stated in the response.
   */
  drug_match?: "broad" | "name_only";
  /**
   * Include the step list in `meta.debug.trace`.
   */
  include_trace?: boolean;
  /**
   * false bypasses the plan cache and the response cache for this request; the registry-call cache stays.
   */
  use_cache?: boolean;
}
/**
 * A typed plan to answer without a model: the body of `POST /v1/analyses`.
 *
 * Nothing is checked against a question; the plan is validated for shape and limits only. Posting
 * `{"plan": meta.plan, "options": meta.options}` from an earlier response reproduces its visualization
 * for the same data timestamp.
 */
export interface AnalysisRequest {
  plan: QueryPlan;
  options?: RequestOptions;
}
/**
 * An answer drawn as a chart, a number or a table.
 */
export interface VisualizationResponse {
  spec_version: "1.0";
  kind: "visualization";
  /**
   * A one-sentence headline computed from the data.
   */
  message: string;
  visualization: Visualization;
  clarification: null;
  /**
   * Exactly the trials cited in the data, keyed by NCT ID.
   */
  references: {
    [k: string]: TrialReference;
  };
  meta: Meta;
}
/**
 * One row per (x, series), following `x.domain`; with a series every combination is present.
 */
export interface BarChart {
  type: "bar_chart";
  title: string;
  /**
   * Scope, number of trials, data date and any subset the chart is limited to.
   */
  subtitle: string | null;
  /**
   * A drawing hint; x is the category axis either way.
   */
  orientation: "vertical" | "horizontal";
  /**
   * A grouped bar chart is `series` set with `none`; `stacked` only for an exclusive series.
   */
  stack: "none" | "stacked";
  encoding: BarChartEncoding;
  data: Datum[];
}
export interface BarChartEncoding {
  x: CategoryChannel;
  y: QuantitativeChannel;
  series: CategoryChannel | null;
  tooltip: FieldDef[];
}
/**
 * A channel of labelled values; colour index i belongs to `domain[i]`.
 */
export interface CategoryChannel {
  field: string;
  type: "nominal" | "ordinal";
  title: string;
  /**
   * Every value in display order: axis, legend and colour index.
   */
  domain: string[];
  sort: ChannelSort | null;
  /**
   * false: a trial can fall under several values, so values add up to more than the trials; never draw such a channel as parts of a whole.
   */
  is_exclusive: boolean;
}
/**
 * How a category axis was ordered. Informational: `domain` and row order are authoritative.
 */
export interface ChannelSort {
  by: "value" | "label" | "natural";
  order: "ascending" | "descending";
}
/**
 * A numeric channel.
 */
export interface QuantitativeChannel {
  field: string;
  type: "quantitative";
  title: string;
  /**
   * A plural noun: trials, participants, months, sites.
   */
  unit: string | null;
  /**
   * The closed set of number formats of v1.
   */
  format: (",d" | ".1f" | ".1%") | null;
  /**
   * log only when every value is above zero.
   */
  scale: "linear" | "log";
}
/**
 * A displayed field: a tooltip entry or a table column.
 */
export interface FieldDef {
  field: string;
  title: string;
  type: "nominal" | "ordinal" | "quantitative" | "temporal";
  unit: string | null;
  format: (",d" | ".1f" | ".1%") | null;
  /**
   * A row key holding a URL to link this value to.
   */
  href_field: string | null;
}
/**
 * A data row: the fields named by the encoding, plus the three reserved keys below.
 *
 * The one contract model that allows extra keys, restricted to scalars. A renderer reads a field
 * through its encoding, and never sorts, filters or computes.
 */
export interface Datum {
  /**
   * Evidence for at most `max_per_datum` trials; [] when disabled.
   */
  citations: Citation[];
  /**
   * Distinct trials behind this datum; never null.
   */
  citation_count: number;
  /**
   * An API URL that returns exactly those trials, or null when none can.
   */
  source_url: string | null;
  [k: string]: string | number | boolean | null | Citation[];
}
/**
 * A pointer into the trial record that a value was computed from.
 */
export interface Citation {
  /**
   * Key into the top-level `references` map.
   */
  nct_id: string;
  /**
   * Path in `GET /api/v2/studies/{nct_id}` with [i] for list items, addressing one value.
   */
  field: string;
  /**
   * The value at that path, verbatim; numbers and booleans in JSON notation. Null means the field is absent and the absence is the evidence.
   */
  excerpt: string | null;
}
/**
 * One row per (period, series), ascending and zero-filled.
 */
export interface TimeSeries {
  type: "time_series";
  title: string;
  subtitle: string | null;
  mark: "line" | "bar" | "area";
  /**
   * Always `none` for lines.
   */
  stack: "none" | "stacked";
  encoding: TimeSeriesEncoding;
  data: Datum[];
}
export interface TimeSeriesEncoding {
  x: TemporalChannel;
  y: QuantitativeChannel;
  series: CategoryChannel | null;
  tooltip: FieldDef[];
}
/**
 * A time axis. Labels are YYYY, YYYY-Qn or YYYY-MM, ascending with no gaps; never parse them as dates.
 */
export interface TemporalChannel {
  field: string;
  type: "temporal";
  title: string;
  time_unit: "year" | "quarter" | "month";
}
/**
 * One row per bin, contiguous and ascending. Bins may be uneven: draw one bar per row using the label.
 */
export interface Histogram {
  type: "histogram";
  title: string;
  subtitle: string | null;
  encoding: HistogramEncoding;
  data: Datum[];
}
export interface HistogramEncoding {
  x: QuantitativeChannel;
  x2: FieldRef;
  y: QuantitativeChannel;
  label: FieldRef;
  tooltip: FieldDef[];
}
/**
 * A reference to a row key.
 */
export interface FieldRef {
  field: string;
}
/**
 * One row per trial; each row cites itself with the fields its coordinates came from.
 */
export interface ScatterPlot {
  type: "scatter_plot";
  title: string;
  subtitle: string | null;
  encoding: ScatterPlotEncoding;
  data: Datum[];
}
export interface ScatterPlotEncoding {
  x: QuantitativeChannel;
  y: QuantitativeChannel;
  series: CategoryChannel | null;
  size: QuantitativeChannel | null;
  label: FieldDef | null;
  tooltip: FieldDef[];
}
/**
 * Nodes and links; `source` and `target` of a link are node ids.
 */
export interface NetworkGraph {
  type: "network_graph";
  title: string;
  subtitle: string | null;
  is_directed: false;
  layout: "force" | "bipartite";
  encoding: NetworkEncoding;
  data: NetworkData;
}
export interface NetworkEncoding {
  nodes: NetworkNodeEncoding;
  edges: NetworkEdgeEncoding;
}
export interface NetworkNodeEncoding {
  label: FieldRef;
  /**
   * With the `bipartite` layout its domain has exactly two values, the two sides.
   */
  color: CategoryChannel | null;
  /**
   * Map to node area.
   */
  size: QuantitativeChannel | null;
  tooltip: FieldDef[];
}
export interface NetworkEdgeEncoding {
  /**
   * Map to stroke width.
   */
  weight: QuantitativeChannel | null;
  tooltip: FieldDef[];
}
export interface NetworkData {
  nodes: Node[];
  edges: Edge[];
}
/**
 * A network node: `label`, `entity_type` and `trial_count` are its other keys.
 */
export interface Node {
  /**
   * Evidence for at most `max_per_datum` trials; [] when disabled.
   */
  citations: Citation[];
  /**
   * Distinct trials behind this datum; never null.
   */
  citation_count: number;
  /**
   * An API URL that returns exactly those trials, or null when none can.
   */
  source_url: string | null;
  id: string;
  [k: string]: string | number | boolean | null | Citation[];
}
/**
 * A network link: `trial_count` is its other key.
 */
export interface Edge {
  /**
   * Evidence for at most `max_per_datum` trials; [] when disabled.
   */
  citations: Citation[];
  /**
   * Distinct trials behind this datum; never null.
   */
  citation_count: number;
  /**
   * An API URL that returns exactly those trials, or null when none can.
   */
  source_url: string | null;
  id: string;
  source: string;
  target: string;
  [k: string]: string | number | boolean | null | Citation[];
}
/**
 * One row per record; `href_field` names a row key holding a URL.
 */
export interface Table {
  type: "table";
  title: string;
  subtitle: string | null;
  encoding: TableEncoding;
  data: Datum[];
}
export interface TableEncoding {
  /**
   * In display order.
   */
  columns: FieldDef[];
}
/**
 * A single number, with citations and `source_url` like any datum.
 */
export interface Metric {
  type: "metric";
  title: string;
  subtitle: string | null;
  encoding: MetricEncoding;
  /**
   * Exactly one row.
   *
   * @minItems 1
   * @maxItems 1
   */
  data: [Datum];
}
export interface MetricEncoding {
  value: QuantitativeChannel;
}
export interface TrialReference {
  /**
   * The brief title, verbatim.
   */
  title: string;
  /**
   * https://clinicaltrials.gov/study/{nct_id}
   */
  url: string;
  scope_evidence: ScopeEvidence[];
}
/**
 * Why a trial is in scope: the first fetched field that contains an entity's words.
 */
export interface ScopeEvidence {
  entity_kind: "drug" | "condition" | "sponsor" | "country" | "term";
  /**
   * The user's words.
   */
  entity_text: string;
  /**
   * Path of the first fetched field that contains them.
   */
  field: string | null;
  /**
   * The value at that path; both null means matched by the registry's own search.
   */
  excerpt: string | null;
}
/**
 * Everything about the answer other than what is drawn. A renderer needs nothing from it.
 */
export interface Meta {
  request_id: string;
  generated_at: string;
  /**
   * As sent, after whitespace normalisation; null for `POST /v1/analyses`.
   */
  query: string | null;
  filters: AppliedFilters;
  /**
   * Null when no plan could be produced.
   */
  interpretation: Interpretation | null;
  /**
   * The canonical plan, defaults explicit.
   */
  plan: QueryPlan | null;
  options: RequestOptions;
  planner: PlannerInfo;
  conversation: Conversation;
  /**
   * Plain-language choices made where the question was open.
   */
  assumptions: string[];
  warnings: Note[];
  /**
   * Null when no upstream request was made.
   */
  source: Source | null;
  counts: Counts | null;
  truncation: Truncation;
  citations: CitationsInfo;
  suggested_followups: LabeledRequest[];
  cache: CacheInfo;
  timing: Timing;
  /**
   * Null when `options.include_trace` is false.
   */
  debug: Debug | null;
}
/**
 * The effective scope in request field names: it can be sent back as request fields.
 */
export interface AppliedFilters {
  drug_name: string[];
  condition: string[];
  sponsor: string[];
  country: string[];
  term: string[];
  trial_phase: ("EARLY_PHASE1" | "PHASE1" | "PHASE2" | "PHASE3" | "PHASE4" | "NA")[];
  status: (
    | "NOT_YET_RECRUITING"
    | "RECRUITING"
    | "ENROLLING_BY_INVITATION"
    | "ACTIVE_NOT_RECRUITING"
    | "COMPLETED"
    | "SUSPENDED"
    | "TERMINATED"
    | "WITHDRAWN"
    | "AVAILABLE"
    | "NO_LONGER_AVAILABLE"
    | "TEMPORARILY_NOT_AVAILABLE"
    | "APPROVED_FOR_MARKETING"
    | "WITHHELD"
    | "UNKNOWN"
  )[];
  study_type: ("INTERVENTIONAL" | "OBSERVATIONAL" | "EXPANDED_ACCESS")[];
  sponsor_class: ("NIH" | "FED" | "OTHER_GOV" | "INDIV" | "INDUSTRY" | "NETWORK" | "AMBIG" | "OTHER" | "UNKNOWN")[];
  intervention_type: (
    | "BEHAVIORAL"
    | "BIOLOGICAL"
    | "COMBINATION_PRODUCT"
    | "DEVICE"
    | "DIAGNOSTIC_TEST"
    | "DIETARY_SUPPLEMENT"
    | "DRUG"
    | "GENETIC"
    | "PROCEDURE"
    | "RADIATION"
    | "OTHER"
  )[];
  sex: ("FEMALE" | "MALE" | "ALL")[];
  age_group: ("CHILD" | "ADULT" | "OLDER_ADULT")[];
  allocation: ("RANDOMIZED" | "NON_RANDOMIZED" | "NA")[];
  masking: ("NONE" | "SINGLE" | "DOUBLE" | "TRIPLE" | "QUADRUPLE")[];
  primary_purpose: (
    | "TREATMENT"
    | "PREVENTION"
    | "DIAGNOSTIC"
    | "ECT"
    | "SUPPORTIVE_CARE"
    | "SCREENING"
    | "HEALTH_SERVICES_RESEARCH"
    | "BASIC_SCIENCE"
    | "DEVICE_FEASIBILITY"
    | "OTHER"
  )[];
  has_results: ("true" | "false")[];
  intervention_model: ("PARALLEL" | "CROSSOVER" | "FACTORIAL" | "SEQUENTIAL" | "SINGLE_GROUP")[];
  start_year: number | null;
  end_year: number | null;
  date_field: ("start_date" | "primary_completion_date" | "completion_date" | "first_posted_date") | null;
  compare: CompareSpec | null;
  exclude: AppliedExclusions;
}
/**
 * What the answer leaves out, in request field names (`exclude` of the request).
 */
export interface AppliedExclusions {
  drug_name: string[];
  condition: string[];
  sponsor: string[];
  country: string[];
  term: string[];
  status: (
    | "NOT_YET_RECRUITING"
    | "RECRUITING"
    | "ENROLLING_BY_INVITATION"
    | "ACTIVE_NOT_RECRUITING"
    | "COMPLETED"
    | "SUSPENDED"
    | "TERMINATED"
    | "WITHDRAWN"
    | "AVAILABLE"
    | "NO_LONGER_AVAILABLE"
    | "TEMPORARILY_NOT_AVAILABLE"
    | "APPROVED_FOR_MARKETING"
    | "WITHHELD"
    | "UNKNOWN"
  )[];
}
/**
 * How the question was read, resolved and executed.
 */
export interface Interpretation {
  /**
   * Written by code from the plan, so it describes what was run.
   */
  summary: string;
  analysis: "aggregate" | "total" | "relate" | "network" | "trial_list";
  /**
   * Null for relate and trial_list.
   */
  measure: Measure | null;
  /**
   * The first is the axis, the second the series; node kinds for a network.
   */
  group_by: string[];
  compare: CompareSpec | null;
  time_granularity: ("year" | "quarter" | "month") | null;
  counting_unit: "trial";
  entities: EntityResolution[];
  adjustments: Adjustment[];
  strategy: StrategyStep[];
  /**
   * The rule of the visualization-type table that fired.
   */
  chart_rationale: string;
}
export interface Measure {
  aggregate: "count" | "median" | "mean" | "sum";
  of: "trials" | "enrollment" | "duration_months" | "site_count";
  /**
   * What `of` is counted in: trials, participants, months or sites.
   */
  unit: string;
}
/**
 * What the registry made of one entity of the plan.
 */
export interface EntityResolution {
  kind: "drug" | "condition" | "sponsor" | "country" | "term";
  /**
   * The kind the plan named. It differs from `kind` when the registry's counts decided which of drug, condition or term the words are.
   */
  planned_kind: "drug" | "condition" | "sponsor" | "country" | "term";
  source: "question" | "request_field" | "plan";
  /**
   * The words used.
   */
  text: string;
  /**
   * After `essie.literal()`, or the registry's country name.
   */
  term_searched: string;
  definition:
    | "intervention_search"
    | "intervention_name"
    | "condition_search"
    | "lead_sponsor_search"
    | "country_exact"
    | "term_search";
  status: "ok" | "low_match" | "ambiguous" | "no_match" | "matches_everything";
  trials_matched: number;
  /**
   * Drug, condition and term readings: the count of `AREA[InterventionName]`.
   */
  strict_name_matches: number | null;
  /**
   * Drug, condition and term readings: the count of `AREA[Condition]`.
   */
  condition_name_matches: number | null;
  /**
   * Drug and condition readings: the registry's own term for the trials found, when it covers far more trials than the wording did.
   */
  registry_term: RegistryTerm | null;
  other_readings: OtherReading[];
  /**
   * Sponsors only.
   */
  candidates: SponsorCandidate[];
}
/**
 * The vocabulary term the registry itself most often assigns to the trials a wording matched.
 */
export interface RegistryTerm {
  /**
   * A MeSH term as the registry's records list it.
   */
  term: string;
  /**
   * The trials that carry this term in the registry.
   */
  trials_matched: number;
  /**
   * The share of the sampled matching trials that carry it.
   */
  sample_share: number;
}
/**
 * The count if the words were read as another kind of entity.
 */
export interface OtherReading {
  kind: "drug" | "condition" | "sponsor" | "country" | "term";
  trials_matched: number;
}
/**
 * A distinct lead-sponsor name in a 200-row sample, with its share of the sample.
 */
export interface SponsorCandidate {
  value: string;
  sample_share: number;
}
/**
 * A change the service made to the plan, and what it did.
 */
export interface Adjustment {
  code: string;
  path: string;
  message: string;
  action: "dropped" | "replaced" | "clamped" | "defaulted" | "repaired" | "kept";
}
/**
 * How the trials of one series were fetched.
 */
export interface StrategyStep {
  series: string | null;
  name: "sorted_page" | "walk" | "count_fan_out" | "sample_then_recount" | "none";
  reason: string;
  upstream_requests: number;
}
/**
 * How the plan was produced.
 */
export interface PlannerInfo {
  mode: "llm" | "structured" | "supplied_plan";
  /**
   * The snapshot the model alias resolved to.
   */
  model: string | null;
  reasoning_effort: string | null;
  prompt_version: string | null;
  attempts: number;
  is_repaired: boolean;
  is_fallback: boolean;
  usage: Usage | null;
}
/**
 * Token counts of one model call.
 */
export interface Usage {
  input_tokens: number;
  output_tokens: number;
  reasoning_tokens: number;
  cached_tokens: number;
}
/**
 * How the answer relates to the previous turn, written by code from the two plans.
 */
export interface Conversation {
  /**
   * True when the request carried a previous turn and the answer kept something of it or completed a clarification; false for a new question and when there was no previous turn.
   */
  is_follow_up: boolean;
  /**
   * What the new plan kept unchanged, e.g. 'drug: pembrolizumab'.
   */
  carried_over: string[];
  /**
   * What the new plan added, removed or replaced, e.g. 'split by phase'.
   */
  changed: string[];
}
/**
 * A data-quality or completeness caveat; `code` is one of the stable warning codes.
 */
export interface Note {
  code: string;
  message: string;
}
/**
 * The registry the data came from, and every request made to it.
 */
export interface Source {
  name: "ClinicalTrials.gov";
  url: "https://clinicaltrials.gov";
  /**
   * From `GET /version`, verbatim.
   */
  api_version: string;
  /**
   * From `GET /version`, verbatim; it has no offset.
   */
  data_timestamp: string;
  retrieved_at: string;
  study_url_template: "https://clinicaltrials.gov/study/{nct_id}";
  record_url_template: "https://clinicaltrials.gov/api/v2/studies/{nct_id}";
  fhir_url_template: "https://clinicaltrials.gov/api/v2/studies/{nct_id}?format=fhir.json";
  requests: UpstreamRequest[];
}
/**
 * One request to ClinicalTrials.gov, in the order issued.
 */
export interface UpstreamRequest {
  method: "GET";
  url: string;
  status: number;
  duration_ms: number;
  total_count: number | null;
  records_returned: number | null;
  is_cached: boolean;
  origin: "resolution" | "probe" | "execution";
}
export interface Counts {
  /**
   * Rows, or nodes plus links.
   */
  data_points: number;
  series: SeriesCounts[];
  /**
   * Filled for a two-group comparison.
   */
  trials_in_several_series: number | null;
}
/**
 * `trials_matched = trials_analyzed + the sum of trials_excluded counts` always holds.
 */
export interface SeriesCounts {
  /**
   * Null for a single scope.
   */
  label: string | null;
  trials_matched: number;
  trials_analyzed: number;
  trials_excluded: ExclusionCount[];
}
/**
 * Trials of a series that were not drawn, and why.
 */
export interface ExclusionCount {
  reason: string;
  count: number;
  message: string;
}
export interface Truncation {
  is_truncated: boolean;
  items: TruncationItem[];
}
export interface TruncationItem {
  scope: "categories" | "series" | "periods" | "nodes" | "edges" | "points" | "rows";
  shown: number;
  total: number;
  rule: string;
}
export interface CitationsInfo {
  is_enabled: boolean;
  max_per_datum: number;
  /**
   * Which trials are cited, as the strategy chose them.
   */
  selection: string;
  /**
   * The size of `references`.
   */
  trials_cited: number;
}
/**
 * A complete request body a button can post; built by rules, never by the model.
 */
export interface LabeledRequest {
  label: string;
  request: QueryRequest;
}
export interface CacheInfo {
  is_plan_cached: boolean;
  is_response_cached: boolean;
  /**
   * When a cached response was first built; null on a fresh one.
   */
  cached_at: string | null;
}
export interface Timing {
  total_ms: number;
  plan_ms: number;
  resolve_ms: number;
  fetch_ms: number;
  build_ms: number;
}
export interface Debug {
  trace: TraceStep[];
}
/**
 * One step of the run. `detail` is outside the stability promise.
 */
export interface TraceStep {
  index: number;
  type: "plan" | "validate" | "repair" | "resolve_entity" | "probe" | "strategy" | "execute" | "build";
  summary: string;
  duration_ms: number;
  /**
   * Indexes into `meta.source.requests`.
   */
  request_indexes: number[];
  detail: {
    [k: string]: unknown;
  };
}
/**
 * The service needs a name or a choice before it can answer.
 */
export interface ClarificationResponse {
  spec_version: "1.0";
  kind: "clarification";
  message: string;
  visualization: null;
  clarification: Clarification;
  references: {
    [k: string]: TrialReference;
  };
  meta: Meta;
}
export interface Clarification {
  reason: "missing_entity" | "unknown_value" | "ambiguous_request" | "could_not_interpret" | "too_broad";
  /**
   * Names of request fields that would settle it; may be empty.
   */
  missing_fields: string[];
  /**
   * Complete request bodies a button can post; may be empty.
   */
  options: LabeledRequest[];
}
/**
 * Nothing to draw: `no_data` when the plan ran and matched nothing, `unsupported` when it cannot run.
 */
export interface MessageResponse {
  spec_version: "1.0";
  kind: "no_data" | "unsupported";
  message: string;
  visualization: null;
  clarification: null;
  references: {
    [k: string]: TrialReference;
  };
  meta: Meta;
}
/**
 * The body of every non-2xx response, from the backend and from the frontend's proxy.
 */
export interface ErrorResponse {
  error: ErrorBody;
}
export interface ErrorBody {
  code:
    | "invalid_request"
    | "not_found"
    | "method_not_allowed"
    | "planner_unavailable"
    | "upstream_unavailable"
    | "upstream_rate_limited"
    | "upstream_timeout"
    | "deadline_exceeded"
    | "internal_error"
    | "backend_unreachable";
  message: string;
  /**
   * `errors[]` of {path, code, message} for invalid_request; `reason` for planner_unavailable; otherwise empty.
   */
  details: {
    [k: string]: unknown;
  };
  request_id: string;
  is_retryable: boolean;
}
